### PR TITLE
Add auditor client capability (Web)

### PR DESCRIPTION
**Pull request by jnmt**
This patch set provides auditor client capabilities. CI testing will be passed after https://github.com/scalar-labs/scalardl-javascript-sdk-base/pull/57 is merged. Also, then I will update package-lock.json.

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by supl — COMMENTED** [review]
Thank you.
It's LGTM.
I guess we can do the same things with node package.
- update CircleCI 2.1 to remove the docker related pipeline
- update scalardl-sample URL
- update REAME.md if necessary

**Comment by supl** [comment]
> Thank you.
> It's LGTM.
> I guess we can do the same things with node package.
> 
> * update CircleCI 2.1 to remove the docker related pipeline
> * update scalardl-sample URL
> * update REAME.md if necessary

Let me do the 1 and the 2

**Comment by supl** [comment]
The automatic NPM registry publishing workflow is removed.

**Comment by supl** [comment]
This PR also change the Circle CI workflow.
Now it only tries to publish this package to NPM registry when a tag v[0-9]+.[0-9]+.[0-9]+ is pushed :)

**Comment by supl** [comment]
@jnmt 
Jun,
When I merged master into this branch, I got some conflicts at `package-lock.json` file, so I recreated it.
The `package-lock.json` is now changed to version 2 (`lockfileVersion: 2`) because my local npm is 7.
I think it should be ok with npm 6.
Just for your information.
Thank you :)

**Comment by feeblefakie** [comment]
@supl The CI fails. Can you take a look? (is it dependent on another PR?)

**Comment by supl** [comment]
> @supl The CI fails. Can you take a look? (is it dependent on another PR?)

Yes.
It failed on download SDK base (is not released yet)
But, I will get back to this PR if it has another fails besides download dependencies.

**Comment by supl** [comment]
@feeblefakie @jnmt
The CI issue is fixed 👯

**Review by supl — APPROVED** [review]
It's an LGTM.
Thank you :)

**Review by feeblefakie — APPROVED** [review]
Still LGTM! Thank you!

**Comment by feeblefakie** [comment]
@supl I'll merge it once the CI passes. Thank you!

**Pull request merged**
